# Generated by Django 2.1.5 on 2020-03-30 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.IntegerField(blank=True, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Ativo'), (2, 'Finalizado'), (3, 'Inativo')], default=1, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('opc', models.CharField(max_length=20, null=True)),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gerente')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinas.Maquinas')),
            ],
            options={
                'verbose_name': 'Etapa do Processo',
                'verbose_name_plural': 'Etapas do Processo',
            },
        ),
        migrations.CreateModel(
            name='Niveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_roteiro', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('montador', models.CharField(blank=True, max_length=50, null=True)),
                ('tempo_estimado', models.CharField(blank=True, max_length=10, null=True)),
                ('tempo_estimado_ms', models.CharField(blank=True, max_length=50, null=True)),
                ('tempo_realizado', models.CharField(blank=True, max_length=10, null=True)),
                ('tempo_realizado_ms', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Pendente'), (2, 'Realizando'), (3, 'Realizado com sucesso'), (4, 'Realizado fora do tempo'), (5, 'Não necessario'), (6, 'Finalizado com pendencias')], default=1, null=True)),
                ('observacao', models.TextField(blank=True, max_length=100, null=True)),
                ('tipo', models.IntegerField(blank=True, choices=[(1, 'Externo'), (2, 'Interno')], null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fim', models.DateTimeField(blank=True, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Procedimento')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.EtapaProcesso', verbose_name='Etapa')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Cargo')),
            ],
            options={
                'verbose_name': 'Procedimento - Atividade',
                'verbose_name_plural': 'Procedimentos - Atividades',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoPadrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_roteiro', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.IntegerField(blank=True, choices=[(1, 'Externo'), (2, 'Interno')], null=True)),
                ('tempo_estimado', models.CharField(blank=True, max_length=10, null=True)),
                ('tempo_estimado_ms', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Niveis')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Cargo')),
            ],
        ),
        migrations.AddField(
            model_name='etapaprocesso',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.OrdemProcesso'),
        ),
        migrations.AlterUniqueTogether(
            name='procedimento',
            unique_together={('processo', 'ordem_roteiro', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='etapaprocesso',
            unique_together={('op', 'etapa')},
        ),
    ]
