# Generated by Django 2.1.5 on 2020-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaprocesso',
            name='linha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
