# Generated by Django 2.1.3 on 2018-11-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20181119_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.Processo'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='status',
            field=models.IntegerField(choices=[(0, 'Outro'), (1, 'Ativo'), (2, 'Inativo')], default=2),
        ),
        migrations.AlterField(
            model_name='setup',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Outro'), (1, 'Externo'), (2, 'Interno')], default=0),
        ),
    ]
