# Generated by Django 2.1.3 on 2020-09-18 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20200710_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaprocesso',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
        ),
        migrations.AlterField(
            model_name='etapaprocesso',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maquinas.Maquinas'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setup.Procedimento'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setup.EtapaProcesso', verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Cargo'),
        ),
        migrations.AlterField(
            model_name='procedimentopadrao',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setup.Niveis'),
        ),
        migrations.AlterField(
            model_name='procedimentopadrao',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='colaborador'),
        ),
        migrations.AlterField(
            model_name='procedimentopadrao',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Cargo'),
        ),
    ]
