# Generated by Django 2.1.3 on 2018-11-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20181119_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
