# Generated by Django 2.1.3 on 2018-11-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20181119_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='cargo',
            new_name='area_responsavel',
        ),
        migrations.AddField(
            model_name='processo',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
