# Generated by Django 2.1.3 on 2018-11-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20181120_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(blank=True, default=True, max_length=20, null=True),
        ),
    ]
