# Generated by Django 2.1.3 on 2018-11-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20181120_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(blank=True, default='Ativo', max_length=20, null=True),
        ),
    ]
