# Generated by Django 2.1.3 on 2018-11-23 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181119_1509'),
        ('maquinas', '0004_auto_20181119_1619'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup', '0007_auto_20181120_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='Ativo', max_length=20, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gerente')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinas.Maquinas')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='processo',
            name='gerente',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='maquina',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='area_responsavel',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='tempo_previsto',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='descricao',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modificado em'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='observacao',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='ordem_roteiro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Cargo'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tempo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tempo_realizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='setup',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Realizando'), (2, 'Realizado com sucesso'), (3, 'Realizada fora do tempo'), (4, 'Realizada com justificativa')], null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.EtapaProcesso'),
        ),
        migrations.DeleteModel(
            name='Processo',
        ),
        migrations.AddField(
            model_name='etapaprocesso',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup.OrdemProcesso'),
        ),
    ]
