# Generated by Django 2.1.3 on 2018-11-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_auto_20181123_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Realizando'), (2, 'Realizado com sucesso'), (3, 'Realizado fora do tempo'), (4, 'Realizado com justificativa')], null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], default=2),
        ),
        migrations.AlterField(
            model_name='setup',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Externo'), (2, 'Interno')], null=True),
        ),
    ]
