# Generated by Django 2.1.3 on 2018-11-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_auto_20181126_0919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='procedimento',
            unique_together={('setup', 'ordem_roteiro')},
        ),
    ]
