# Generated by Django 2.1.3 on 2018-11-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_auto_20181128_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'ordering': ['ordem_roteiro']},
        ),
    ]
