# Generated by Django 2.1.3 on 2018-11-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_auto_20181128_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em'),
        ),
    ]
