# Generated by Django 2.1.3 on 2018-12-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0020_auto_20181129_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'ordering': ['ordem_roteiro'], 'verbose_name': 'Procedimento - Atividade', 'verbose_name_plural': 'Procedimentos - Atividades'},
        ),
    ]
