# Generated by Django 2.1.3 on 2018-12-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0021_auto_20181204_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'verbose_name': 'Procedimento - Atividade', 'verbose_name_plural': 'Procedimentos - Atividades'},
        ),
    ]
