# Generated by Django 2.1.3 on 2018-12-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0022_auto_20181210_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='etapaprocesso',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
