# Generated by Django 2.1.3 on 2019-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0023_auto_20181213_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pendente'), (2, 'Realizando'), (3, 'Realizado com sucesso'), (4, 'Realizado fora do tempo'), (5, 'Não necessario'), (6, 'Finalizado com pendencias')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tempo_estimado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tempo_realizado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
