# Generated by Django 2.1.3 on 2019-01-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0024_auto_20190110_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.EtapaProcesso', verbose_name='Estapa'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Externo'), (2, 'Interno')], null=True),
        ),
        migrations.AlterField(
            model_name='etapaprocesso',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Ativo'), (2, 'Finalizado'), (3, 'Inativo')], default=1, null=True),
        ),
    ]
