# Generated by Django 2.1.3 on 2019-01-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0025_auto_20190113_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimento',
            old_name='etapa',
            new_name='processo',
        ),
    ]
