# Generated by Django 2.1.3 on 2019-01-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0026_auto_20190113_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.EtapaProcesso', verbose_name='Etapa'),
        ),
        migrations.AlterUniqueTogether(
            name='procedimento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='setup',
        ),
    ]
