# Generated by Django 2.1.3 on 2019-01-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0027_auto_20190114_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='created',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='modified',
        ),
    ]
