# Generated by Django 2.1.3 on 2019-01-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0028_auto_20190114_1020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='setup',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='responsavel',
        ),
        migrations.DeleteModel(
            name='Setup',
        ),
    ]
