# Generated by Django 2.1.3 on 2019-01-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0029_auto_20190114_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='procedimento',
            unique_together={('processo', 'ordem_roteiro', 'tipo')},
        ),
    ]
