# Generated by Django 2.1.3 on 2019-01-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0031_auto_20190117_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='tempo_realizado2',
        ),
    ]
