# Generated by Django 2.1.3 on 2019-01-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0032_remove_procedimento_tempo_realizado2'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='tempo_estimado_ms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tempo_realizado_ms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
