# Generated by Django 2.1.3 on 2019-01-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0033_auto_20190124_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='tempo_estimado_ms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tempo_realizado_ms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
