# Generated by Django 2.1.3 on 2019-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0035_auto_20190207_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='montador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
