# Generated by Django 2.1.3 on 2019-10-07 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0036_procedimento_montador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaprocesso',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
        ),
    ]
