# Generated by Django 2.1.3 on 2020-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0037_auto_20191007_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaprocesso',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
