# Generated by Django 2.1.5 on 2021-03-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Maquina',
                'verbose_name_plural': 'Maquinas',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de Maquina',
                'verbose_name_plural': 'Tipos de Maquinas',
            },
        ),
        migrations.AddField(
            model_name='maquinas',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinas.Tipo'),
        ),
    ]
