# Generated by Django 2.1.3 on 2018-11-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maquinhas',
            new_name='Maquinas',
        ),
        migrations.AlterModelOptions(
            name='maquinas',
            options={'verbose_name': 'Maquina', 'verbose_name_plural': 'Maquinas'},
        ),
    ]
