# Generated by Django 2.1.3 on 2018-11-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_auto_20181119_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name': 'Tipo de Maquina', 'verbose_name_plural': 'Tipos de Maquinas'},
        ),
    ]
